# Generated by Django 5.1 on 2025-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_count',
        ),
        migrations.AddField(
            model_name='playlist',
            name='accessCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='vibe',
            field=models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('LATIN', 'Latin'), ('COUNTRY', 'Country'), ('TECHNO', 'Techno'), ('RNB/SOUL', 'R&B/Soul')], default='POP', max_length=10),
        ),
    ]
